name: CI/CD for BFF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instalar dependências
      - name: Install dependencies
        run: npm install

      # Verificar formatação com ESLint
      - name: Lint code
        run: npm run lint

      # Rodar testes unitários
      - name: Run tests
        run: npm run test

      # Build da aplicação
      - name: Build application
        run: npm run build

      # Verificar cobertura de testes
      - name: Test coverage
        run: npm run test:cov

      # Criar versão e tag
      - name: Create version tag
        if: github.ref == 'refs/heads/main'
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: actions@github.com
        run: |
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git fetch --prune --unshallow
          npm run version:patch
          git push origin --tags

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to AWS EC2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: sa-east-1
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          cd /home/ec2-user/CAFE-02_bff
          git pull origin main
          npm install
          npm run build
          pm2 restart bff
          EOF
